### ISSUE TITLE
.gitignoreのついか

### ISSUE THREAD

**Issue by i17305** [ichi-raven/Cpps-challenge#3]
`/.vs/C++'s chalenge/v15`
も
`/Debug`
も
`/x64/Debug/`
もｲﾗﾈ

**Comment by ichi-raven** [comment]
debugっていらないんですか？

**Comment by ichi-raven** [comment]
あと.gitignoreってどうやって作るんでしょう

**Comment by i17305** [comment]
ビルドのバイナリをあげるのはよろしくないで

.gitignoreは単なるテキストファイルやで
Windowsだと名前で作成できない恐れあるけど
